### ISSUE TITLE
Stopped working after DSM 7.2.2 upgrade

### ISSUE THREAD

**Issue by benmargolin** [dvcol/synology-download#233]
### Affected part

Connection (login/fetching), Context menu (right click on links), Content script (inside the page)

### Extension version

3.16.4

### DSM version

DSM 7.2.2-72806 Update 1

### Browser version

Chrome 130.0.6723.92

### Description

Maybe protocol changed in DSM 7.2.2? That's the main thing I believe changed since it was last working (although also Chrome and the extension have updated so... could be those as well).

I'm connecting to http://<local private ip>:5000, "test login" says it works. But I can't add magnet URIs, usually just silent, but sometimes has an error "Failed to create download t..." with details "Invalid session. <url of magnet>". See log below.

When I go to the options and do 'test login' it gives "Login attempt successful".

### Steps to Reproduce the Issue

Click on a magnet, get error (used to add to dl client on nas).
Tried log out then test login (works ok), then click on magnet again, got "Login required" now instead of the error from the description above.

### Failure Logs

```console
background.entry.js:1 [2024-11-05T21:48:47.746Z - background] Polling service failed to fetch statistics Vu: The logged in session does not have permission
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:134135
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:39383
    at t._next (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:24456)
    at t.next (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:22559)
    at t._next (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:22942)
    at t.next (chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:22559)
    at chrome-extension://ebbdkledlkjpgbbmmopgbnnjmklnkcef/entry/background.entry.js:1:27906
```

**Comment by mountbatt** [comment]
same her

**Comment by raghavthakur** [comment]
Also having a similar issue. However, on DSM 7.2.1-69057 Update 5. I'm able to login in locally to the DSM but cannot send any new downloads to the NAS. I've read on [Reddit](https://www.reddit.com/r/synology/comments/mfgtki/download_station_chrome_extension_issue/) that this is because the new updated Download Station v4.0.3-4720 (https://archive.synology.com/download/Package/DownloadStation/4.0.3-4720) has a change that breaks the Chrome extension.
![Screenshot 2024-11-18 at 11 42 54 AM](https://github.com/user-attachments/assets/fa9fbe60-de0f-4eb8-a28d-ded1d185b799)

**Comment by dvcol** [comment]
👀 

I'll try to make some time next week to look into this. 

I've been puting off updating to 7.2 because I currently use Synology VideoStation that has been deprecated, so unsure how I'll go about trying to reproduce though 🤔

**Comment by raghavthakur** [comment]
Perhaps I can send you some logs that will help debug the issue? Or link the source code line number here that connects to DSM and I can take a look at the code.

**Comment by dvcol** [comment]
I'll have to bite the bullet at some point, especially with the recent security issues in DSM <= 7.2.

But If you want to have a look, all the clients are setup in the [query service](https://github.com/dvcol/synology-download/blob/main/src/services/query/query.service.ts), with the [login logic here ](https://github.com/dvcol/synology-download/blob/d84ec7ef9f5c132e5359924b883a2746b0aa7ea7/src/services/query/query.service.ts#L294-L410).

However, since test-login and login passes, I have an inkling that there might be a change in cookie handling or SID managment. If it's the case than the issue might be in the header config in the http [clients here ](https://github.com/dvcol/synology-download/blob/main/src/services/http/synology.service.ts) or [here](https://github.com/dvcol/synology-download/blob/main/src/services/http/synology-auth.service.ts).

Sadly, I never sucessfully found any recent-ish API doc for [DownloadStation](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf) (last one from 2012). 
But there is the [FIleStation](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf) one that is somewhat recent (2023).

So we might need to reverse engeneer the calls by spying on the DownloadStation WebUI API calls to some extent to see what changed

**Comment by benmargolin** [comment]
BTW, this is working for me again, on DSM 7.2.2-72806 Update 1. I don't know what changed (did a new version of the extension get published?). Or maybe just restarting Chrome enough times / rebooting the machine fixed it? But the extension is working as intended at this point.

Maybe Chrome had some minor cookie bug that's been resolved? Or maybe it's broken for other folks still?

**Comment by dvcol** [comment]
> BTW, this is working for me again, on DSM 7.2.2-72806 Update 1. I don't know what changed (did a new version of the extension get published?). Or maybe just restarting Chrome enough times / rebooting the machine fixed it? But the extension is working as intended at this point.
> 
> Maybe Chrome had some minor cookie bug that's been resolved? Or maybe it's broken for other folks still?

Um, interesting, this leads me to believe that might just be a cookie issue then, by default, we use cookie session if one is active and if not we fallback to _sid tokens.

Maybe session got invalidated between upgrade and the server never invalidated the http cookie that chrome uses for the sessions ?

**Comment by dvcol** [comment]
> Still broken for me with the same symptoms on DSM 7.1.1-42962 Update 6.

Can you try:

1. Clearing cookie for the session
```
right-click > inspect pop-up >  Application > Storage > Clear site data (tick including third-party cookies
```
![image](https://github.com/user-attachments/assets/fcbaf064-d615-4ac5-b87f-db43a393481e)

2. Clean extension storage
```
Settings > chrome storage snapshot > clear local & clear sync
```
![image](https://github.com/user-attachments/assets/73d34788-80f7-4bf0-8784-dc548f6d09a6)

3. Restart chrome

**Warning: this will reset all extension settings, so you will need to re-do your config if you change anything form default**

**Comment by ynamite** [comment]
I had the same error, encountered after updating to the latest DSM from 6 to 7.
Clearing the cookies for the extension seems to have fixed the problem.

**Comment by dvcol** [comment]
For info, I pushed a new release that support SID token for session instead of cookie, which might help things.

But this issue is quite nebulous as I never sucessfully reproduced it on my side :/

**Comment by BourgeoisDirk** [comment]
Hey, This extension seems to be exactly what I've been looking for.. But am experiencing the exact same issues mentioned in this thread.
My NAS was updated to latest DSM last week, this is a fresh Windows 11 Install and the first time i use this Extension.
Login works fine, i can see all my previous downloads, but cannot add a new download via the browser.

@dvcol , i can confirm after changing from Cookie to SID that the issues mentioned before instantly disappeared.

I would like to make 2 feature requests though:
1) When removing all options from the menu except "Send to Synology", it still opens a menu although there is only 1 option. Would be nice to skip the menu and just instantly have it sent to Synology
2) could this also be made available for .torrent files (not everything has magnet links) 
>> Magnets & Torrents both work when RClick > Menu > "Add to Synology Diskstation", but having the option to skip all of this would be nice. Can you intercept the Magnet and Torrent clicks and automatically send them to Diskstation ? No menu's, no right click ?

Kind regards, great job

**Comment by dvcol** [comment]
> I would like to make 2 feature requests though:

IMO, this is outside of the scope of this issue, please kindly open a separate [issue or feature request](https://github.com/dvcol/synology-download/issues) with reproduction step and as much info as you can provide :)

> When removing all options from the Quick Menu except "Send to Synology", it still opens a menu although there is only 1 option. Would be nice to skip the menu and just instantly have it sent to Synology

This shouldn't happen, if there is only one element in quick menu it should skip the dropdown and directly start the task or open the popup/modal (depending on settings). 

If it's not the case, please open a ticket with a reproduction case.

> could this also be made available for .torrent files (not everything has magnet links)

Magnet link interception is done by parsing the dom and isolating href and <a> anchors and identifying valid magnet links (because of limitations in chrome's link handler api).

By definition this method is very brittle as it requires sites to not obscure their links or bounce redirects. It also makes it almost impossible to indentify if a link is a torrent or not (especially if the download is initiated by js which is often the case for non link downloads).

To bypass this, the intecept feature waits for chrome to starts a download, then intercept it and if it match the intecept pattern, cancel the download and forward it to synology.

This also is quite brittle as it's requires the meta data of the payload to be valid and to include torrent MIME type.

Given this limitations, it would be complicated to handle more edge cases.

* Note: My testbed for this is [archlinux downloads links,](https://archlinux.org/download/) if you can intercept it then it's a limitation of the app, if not, then something might be wrong with your install/setup of the appplication

* Note: An alternative would be to query the servers themself and follow the redirects to the final download, but this requires broader permissions and an increased complexity that I'm not able to pursue at the moment sorry.

**Comment by BourgeoisDirk** [comment]
Hey, thanks for your feedback ! :)
I will take it to heart, and follow your guidance to create and elaborate on separate issue/feature request.

About the Magnet/Torrent intercept, i had no idea it would be so complicated, but i understand.
I am using Microsoft Edge, Version 133.0.3065.59 (Official build) (64-bit) (if this helps), i have not gotten the torrent intercept to work yet. Have it enabled, download a torrent file, but the download of the file is not cancelled or forwarded.
Would it perhaps be possible to make a "whitelist" for certain sites ? Any Magnet/Torrent coming from this site to have forwarded to Synology instead ?
Just wondering, again i understand if it would lot be possible, but would be cool :)

I love your work, thanks for making this ! 🤗

**Comment by Helveg** [comment]
Since the issue is still open, I'd like to weigh in here with my experience. DSM 7.2, got Download Station going and installed this extension, login works like others reported but pretty much all other features yield the "invalid session" error. Switching from `Cookie` to `SID` worked for me too:

![Image](https://github.com/user-attachments/assets/9f454eaa-f602-4064-8aac-d30c67ba8290)

Perhaps since the default behavior seems to be that new users run into a brick wall with this, `SID` should be the default setting?

**Comment by f1oren** [comment]
Even with switching from Cookie to SID, I'm still getting error 'Failed to load folder'. 

<img width="720" height="592" alt="Image" src="https://github.com/user-attachments/assets/390ef190-d24b-4c02-9c7d-53badf884f77" />

<img width="720" height="592" alt="Image" src="https://github.com/user-attachments/assets/ec725a95-3a9e-4294-8b4f-08f6d2adfbad" />

<img width="720" height="592" alt="Image" src="https://github.com/user-attachments/assets/520487f8-b2d7-435a-b396-725659d93b52" />

**Comment by BourgeoisDirk** [comment]
@f1oren Just a quick question, is it possible that the user you are logged in with does not have the proper permissions to the correct folders ?
I may be wrong, just wondering. Kind regards, hope you get if fixed

**Comment by CptTwinkie** [comment]
I had the same issue after the 7.2.2-72806 update. I tried all of the things...restarting the NAS, restarting my PC, switching to cookies, clearing browser data. I tried all of those in different orders, and nothing worked. I could always log in, but the GUI always showed that I wasn't logged in.

So, after doing all of that, I remembered I'm a programmer, and I started thinking like one. 
- If the extension works most of the time, then it's basically functional
- Once it becomes non-functional, clearing all settings doesn't fix it

My first thought was that the NAS was blocking it. That didn't really hold up after a restart and the successful logins.
My second thought was that if it's not the NAS, and the data is cleared, what state could persist that would block normal operation!?

That's when I reached the only correct conclusion. The data wasn't cleared. Even though all storage data from Chrome had been removed, it was still retaining some state.

I cleared the storage and uninstalled the extension. I restarted Chrome and reinstalled it. It worked.

I guess that either there is more storage somewhere (not likely) or that the extension was holding its state in memory and saving back to storage after the storage was cleared. The other option is that it was pulling sync data. I didn't even think of that until now, and I don't know how to check that.
